# Generated by Django 4.0.3 on 2022-03-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220313_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='geo',
            field=models.CharField(default='https://goo.gl/maps/d1bRXbvRDfRN7NfB8', max_length=255, verbose_name='Геопозиция'),
        ),
    ]
